spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hgugaticar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: qlqjs2763!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true